Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
